### ISSUE TITLE
Embedded DB not added back to odb file

### ISSUE THREAD

**Issue by keif888** [prrvchr/jdbcDriverOOo#10]
**LibreOffice version information**
Version: 24.2.5.2 (X86_64) / LibreOffice Community
Build ID: bffef4ea93e59bebbeaf7f431bb02b1a39ee8a59
CPU threads: 16; OS: Windows 10.0 Build 19045; UI render: Skia/Raster; VCL: win
Locale: en-AU (en_AU); UI: en-GB
Calc: CL threaded

**hsqldb version information**
SELECT CHARACTER_VALUE FROM INFORMATION_SCHEMA.SQL_IMPLEMENTATION_INFO   where IMPLEMENTATION_INFO_NAME = 'DBMS VERSION'  ; = 2.7.3

**Extension version information**
HsqlDriverOOo version 1.0.0 from https://extensions.libreoffice.org/en/extensions/show/27494
jdbcDriverOOo version 1.4.1 from https://github.com/prrvchr/jdbcDriverOOo/releases/tag/v1.4.1

**Issue**
When creating, saving and closing the database in LibreOffice, the hsqldb is not embedded back into the odb file.
Maybe due to version mismatches in what I installed?

**What happened**
The 3 files that make up the hsqldb database were left in the filename.lck folder on close of Base document.
LibreOffice asks to recover the database on startup.

**What was expected**
The files that make up the hsqldb database are added into the database folder within the Base document, and the filename.lck folder is removed from the file system.

**Fix?**
Replace HsqlDriverOOo with HyperSQLOOo version 1.1.3

**Comments**

Please note that the combination below works:
HyperSQLOOo version 1.1.3 from https://github.com/prrvchr/HyperSQLOOo/releases/tag/v1.1.3
jdbcDriverOOo version 1.4.1 from https://github.com/prrvchr/jdbcDriverOOo/releases/tag/v1.4.1
but I had to rename the hsqldb files to match the pattern below from what was in the filename.lck folder:
hsqldb.data
hsqldb.properties
hsqldb.script

to allow the "broken" odb files to load correctly.  (no issues after the rename).

**Comment by prrvchr** [comment]
Hi keif888,

I confirm that you must use version 1.1.3 of HyperSQLOOo.
Version 1.0.0 is obsolete and poses the problem you mentioned.
I advise you to download the extensions from Github and not from the LibreOffice extension site which is not up to date.
