### ISSUE TITLE
 "No module named "packaging"" error while installing

### ISSUE THREAD

**Issue by artem78** [prrvchr/jdbcDriverOOo#4]
When I try to install jdbcDriverOOo package in LibreOffice I see "no module named "packaging"" error.

![Снимок экрана в 2023-11-24 14-01-07](https://github.com/prrvchr/jdbcDriverOOo/assets/8585304/2d4d166e-b872-4f43-a736-cb5e304205fb)

Running this command has no effect:
```
user@pc:~$ pip3 install packaging
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (20.3)
```

LibreOffice version: 6.4.7.2
OS: Linux Mint 20.3 Una (based on Ubuntu 20.04 focal)
Java: openjdk 11.0.20.1 2023-08-24

**Comment by prrvchr** [comment]
Hi,

You are right, the python package `packaging` is missing. I just fixed this problem, version 1.0.6 should work fine.
Do not hesitate to open a new issue if necessary.

**Comment by artem78** [comment]
Thanks a lot for very fast fix! New version installed successfully and works fine.

**Comment by prrvchr** [comment]
> Thanks a lot for very fast fix! New version installed successfully and works fine.

You're welcome. All credit goes to you, this bug has been there for a while... You are the only one who took the time to open an issue to report it to me..
Thank you.
