### ISSUE TITLE
Error "Binary URP bridge disposed during call" when installed in OpenOffice on Windows

### ISSUE THREAD

**Issue by artem78** [prrvchr/jdbcDriverOOo#5]
Hello again.

I have another issue, but when installing your extension to OpenOffice on Windows.

![20231125_195918](https://github.com/prrvchr/jdbcDriverOOo/assets/8585304/0863ea8d-ebf5-4031-90ee-579e379a458d)

OpenOffice 4.1.14, Windows 7 SP1 64bit, JRE Adoptium 11.0.21.9 32bit

**Comment by prrvchr** [comment]
Hi artem78,

Normally I no longer support **OpenOffice**.
OpenOffice still uses a Python 2 version and most of my extensions do not work with Python 2.
I think it's a waste of time to try to make something work with such constraints.
I advise you to migrate to **LibreOffice** and under Windows LibreOffice version 7 minimum.
​

**Comment by artem78** [comment]
> I advise you to migrate to LibreOffice
Thanks for advise, but maybe some old version of extension can works in OpenOffice?

**Comment by prrvchr** [comment]
> Thanks for advise, but maybe some old version of extension can works in OpenOffice?

Yes it should work with old versions of extensions, but that's like trying to make old things work...
Honestly, I don't recommend it...

**Comment by artem78** [comment]
> Is there anything stopping you from migrating to LibreOffice?

Actually no. I used OpenOffice in Windows for many years. In Linux I left as is preinstalled LibreOffice because it is compatible with OpenOffice documents. This is not a problem for me to install LibreOffice on Windows in addition to OpenOffice (or instead of it).

> I think it's a waste of time to try to make something work with such constraints.

In this case you may close this issue report.
