### ISSUE TITLE
Inserting cells from Calc does not work

### ISSUE THREAD

**Issue by Meat12237** [prrvchr/jdbcDriverOOo#7]
Thanks for the many embedded databases.

The data is inserted into the table from Calc as follows:

1.  Table has been copied from Calc onto the clipboard
2.  Then it is pasted into Base’s Table container. In the Table container, right-click to open the context menu for the target table to which the records are to be added. Select "Paste".
3. Then we work with the Import wizard.

After installing jdbcDriverOOo, the Import wizard does not start when working with HyperSQLOOo, as well as with SQLiteOOo. I managed to launch Import wizard after the 6th launch command.

After the Import wizard was working, the data was not inserted.

Please confirm or deny this issue.

**Comment by prrvchr** [comment]
Ok I just released version 1.3.3 of [jdbcDriverOOo](https://prrvchr.github.io/jdbcDriverOOo/).

This version should resolve the copy and paste problem from Calc to Base.

Let me know if everything works correctly for you.

**Comment by prrvchr** [comment]
Without answer I guess it works...
